import React, { useState, useEffect } from "react";

const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:3001";
const API_URL = `${API_BASE}/inventory`;
const AUDIT_LOG_URL = "/audit_log.jsonl"; // served from client/public/

function StatusBadge({ status }) {
  const isAvailable = status === "Available";
  return (
    <span style={{ padding: "4px 10px", borderRadius: "999px", fontSize: "13px" }}>
      {status}
    </span>
  );
}

export default function InventoryList() {
  const [inventory, setInventory] = useState([]);
  const [auditEvents, setAuditEvents] = useState([]);
  const [form, setForm] = useState({ name: "", category: "", quantity: "", status: "Available" });

  function fetchInventory() {
    fetch(API_URL)
      .then((res) => res.json())
      .then((data) => setInventory(data))
      .catch((err) => console.error("Failed to fetch inventory:", err));
  }

  // Reads the audit log generated by reconcile.py (Module 4, Deliverable 3).
  // It's a .jsonl file -- one JSON object per line -- so it's parsed manually
  // rather than with a single res.json() call.
  function fetchAuditLog() {
    fetch(AUDIT_LOG_URL)
      .then((res) => res.text())
      .then((text) => {
        const events = text
          .split("\n")
          .filter((line) => line.trim() !== "")
          .map((line) => JSON.parse(line));
        setAuditEvents(events);
      })
      .catch((err) => console.error("Failed to fetch audit log:", err));
  }

  useEffect(() => {
    fetchInventory();
    fetchAuditLog();
  }, []);

  function handleChange(e) {
    const { name, value } = e.target;
    setForm((prev) => ({ ...prev, [name]: value }));
  }

  function handleSubmit(e) {
    e.preventDefault();
    fetch(API_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...form, quantity: Number(form.quantity) }),
    })
      .then(() => {
        fetchInventory();
        setForm({ name: "", category: "", quantity: "", status: "Available" });
      })
      .catch((err) => console.error("Failed to add item:", err));
  }

  // --- Data science layer: summary metrics computed directly from the
  // already-fetched inventory array, same numbers Section 1's pandas script
  // produces, just recomputed here in JS so the dashboard doesn't need a
  // separate backend endpoint for it. ---
  const totalItems = inventory.length;
  const LOW_STOCK_THRESHOLD = 5;
  const lowStockItems = inventory.filter((item) => item.quantity <= LOW_STOCK_THRESHOLD);
  const byCategory = inventory.reduce((acc, item) => {
    acc[item.category] = (acc[item.category] || 0) + 1;
    return acc;
  }, {});

  // --- ML layer: discrepancies and items needing manual review, straight
  // from reconcile.py's audit log. ---
  const discrepancies = auditEvents.filter((e) => e.event_type === "DISCREPANCY");
  const needsReview = auditEvents.filter((e) => e.event_type === "UNCERTAIN");

  // --- Declared vs. observed: for each inventory item, look up whether the
  // ML pipeline has any observation about it, so both sources of truth are
  // visible side by side rather than only showing the database's version. ---
  function observedStatusFor(itemName) {
    const event = auditEvents.find((e) => e.item === itemName);
    return event ? event.event_type : "No observation";
  }

  return (
    <div style={{ maxWidth: 800, margin: "0 auto", padding: "24px", fontFamily: "sans-serif" }}>
      <h2>Open Project inventory</h2>

      {/* Summary metrics -- Section 1 */}
      <section style={{ marginBottom: "24px" }}>
        <h3>Summary</h3>
        <p>Total items: {totalItems}</p>
        <p>Low stock items (qty ≤ {LOW_STOCK_THRESHOLD}): {lowStockItems.length}</p>
        <ul>
          {Object.entries(byCategory).map(([category, count]) => (
            <li key={category}>{category}: {count}</li>
          ))}
        </ul>
      </section>

      {/* ML system states -- Section 2 */}
      <section style={{ marginBottom: "24px" }}>
        <h3>Flagged discrepancies ({discrepancies.length})</h3>
        {discrepancies.length === 0 ? (
          <p>None</p>
        ) : (
          <ul>
            {discrepancies.map((e, i) => (
              <li key={i}>
                {e.item} (scene {e.scene_id}, confidence {e.confidence}) — {e.recommended_action}
              </li>
            ))}
          </ul>
        )}

        <h3>Needs manual review ({needsReview.length})</h3>
        {needsReview.length === 0 ? (
          <p>None</p>
        ) : (
          <ul>
            {needsReview.map((e, i) => (
              <li key={i}>
                {e.item} (scene {e.scene_id}, confidence {e.confidence})
              </li>
            ))}
          </ul>
        )}
      </section>

      {/* Main table: declared (DB) vs observed (ML) side by side */}
      <table style={{ width: "100%", borderCollapse: "collapse", marginBottom: "32px" }}>
        <thead>
          <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Declared qty (DB)</th>
            <th>Declared status</th>
            <th>Observed (ML)</th>
          </tr>
        </thead>
        <tbody>
          {inventory.map((item) => (
            <tr key={item.id}>
              <td>{item.name}</td>
              <td>{item.category}</td>
              <td>{item.quantity}</td>
              <td><StatusBadge status={item.status} /></td>
              <td>{observedStatusFor(item.name)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h3>Add new item</h3>
      <form onSubmit={handleSubmit} style={{ display: "flex", flexDirection: "column", gap: "10px", maxWidth: 320 }}>
        <input name="name" placeholder="Name" value={form.name} onChange={handleChange} required />
        <input name="category" placeholder="Category" value={form.category} onChange={handleChange} required />
        <input name="quantity" type="number" placeholder="Quantity" value={form.quantity} onChange={handleChange} required />
        <select name="status" value={form.status} onChange={handleChange}>
          <option value="Available">Available</option>
          <option value="Unavailable">Unavailable</option>
        </select>
        <button type="submit">Add item</button>
      </form>
    </div>
  );
}
